import unittest
import zipfile
from decimal import Decimal
from pathlib import Path
from tempfile import TemporaryDirectory

from collection_filtering import (
    build_vodafone_manual_wallet_ledger_summary,
    build_vodafone_manual_wallet_ledger_workbook,
)


class VodafoneManualWalletLedgerTests(unittest.TestCase):
    def test_summary_uses_vodafone_manual_amount_as_disbursement(self):
        rows = [
            {"Id": "VF-1", "Date": "2026-09-01", "Amount": "100.50"},
            {"Id": "VF-2", "Date": "2026-09-02", "Amount": "49.50"},
        ]

        _summary, metrics = build_vodafone_manual_wallet_ledger_summary(
            Decimal("500"), Decimal("-10"), rows
        )

        self.assertEqual(metrics["total_disbursement"], Decimal("150"))
        self.assertEqual(metrics["total_debit"], Decimal("160"))
        self.assertEqual(metrics["wallet_statement_balance"], Decimal("340"))
        self.assertEqual(metrics["disbursement_count"], 2)

    def test_workbook_contains_summary_and_source_sheet(self):
        with TemporaryDirectory() as tmpdir:
            source = Path(tmpdir) / "vodafone_manual.csv"
            output = Path(tmpdir) / "Vodafone_Manual_Wallet_vs_Ledger.xlsx"
            source.write_text(
                "Report generated by Vodafone\n"
                "Id,External id,Date,Status,Type,Amount\n"
                "VF-1,EXT-1,2026-09-01,Successful,Disbursement,125.00\n",
                encoding="utf-8",
            )

            result = build_vodafone_manual_wallet_ledger_workbook(
                output, [source], Decimal("500"), Decimal("25")
            )

            self.assertEqual(result.metrics["total_disbursement"], Decimal("125"))
            self.assertEqual(result.metrics["wallet_statement_balance"], Decimal("400"))
            with zipfile.ZipFile(output) as workbook:
                workbook_xml = workbook.read("xl/workbook.xml").decode("utf-8")
            self.assertIn("Summary", workbook_xml)
            self.assertIn("Vodafone Manual", workbook_xml)


if __name__ == "__main__":
    unittest.main()
